version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14

      - image: cr.yandex/crp3cgu5vnl52hr4ct47/playwright-backend:$CIRCLE_BRANCH
        auth:
          username: json_key
          password: $YA_REGISTRY_KEY
    steps:
      - checkout

      - run: "npm install"

      - run: "npm run test:e2e"

      - store_artifacts:
          path: result.xml