version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:14.17.3

      - image: cr.yandex/crp3cgu5vnl52hr4ct47/playwright-backend:$CIRCLE_BRANCH
        auth:
          username: json_key
          password: $YA_REGISTRY_KEY
    steps:
      - checkout

#      - run: "sudo apt update & sudo apt install -y libnss3"

      - run: "npm install"

      - run: "npm run test:e2e:ci"

      - store_artifacts:
          path: results.xml