version: 2.1

jobs:
  build:
    docker:
      - image: mcr.microsoft.com/playwright:focal

      - image: cr.yandex/crp3cgu5vnl52hr4ct47/playwright-backend:$CIRCLE_BRANCH
        auth:
          username: json_key
          password: $YA_REGISTRY_KEY
    steps:
      - checkout

      - run: "npm install"

      - run: "npm run ci:playwright"

      - run: "npm run ci:cypress"

      - store_artifacts:
          path: results.xml